version: '3.9'

services:
  fp-proxy:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - FPP_SERVER_URL=https://dagsordener.randers.dk/
    volumes:
      - ./src:/code/src
    ports:
      - "8019:5000"
